apiVersion: v1
kind: Service
metadata:
  name: apigtw-loadbalancer-srv
spec:
  type: LoadBalancer
  selector:
    app: ocelotapigateway
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
