apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-inventory-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-inv
  template:
    metadata:
      labels:
        app: mysql-inv
    spec:
      containers:
        - name: mysql
          image: mysql:latest
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql
                  key: SA_PASSWORD
            - name: MYSQL_DATABASE
              value: "savadb_inv"
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: mysqlinvdb
      volumes:
        - name: mysqlinvdb
          persistentVolumeClaim:
            claimName: mysql-inventory-claim
---
apiVersion: v1
kind: Service
metadata:
  name: inv-mysql-clusterip-srv
spec:
  type: ClusterIP
  selector:
    app: mysql-inv
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
---
apiVersion: v1
kind: Service
metadata:
  name: inv-mysql-loadbalancer-srv
spec:
  type: LoadBalancer
  selector:
    app: mysql-inv
  ports:
    - protocol: TCP
      port: 33061
      targetPort: 3306
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-customer-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-cust
  template:
    metadata:
      labels:
        app: mysql-cust
    spec:
      containers:
        - name: mysql
          image: mysql:latest
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql
                  key: SA_PASSWORD
            - name: MYSQL_DATABASE
              value: "savadb_cust"
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: mysqlcustdb
      volumes:
        - name: mysqlcustdb
          persistentVolumeClaim:
            claimName: mysql-customer-claim
---
apiVersion: v1
kind: Service
metadata:
  name: cust-mysql-clusterip-srv
spec:
  type: ClusterIP
  selector:
    app: mysql-cust
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
---
apiVersion: v1
kind: Service
metadata:
  name: cust-mysql-loadbalancer-srv
spec:
  type: LoadBalancer
  selector:
    app: mysql-cust
  ports:
    - protocol: TCP
      port: 33062
      targetPort: 3306
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-order-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-order
  template:
    metadata:
      labels:
        app: mysql-order
    spec:
      containers:
        - name: mysql
          image: mysql:latest
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql
                  key: SA_PASSWORD
            - name: MYSQL_DATABASE
              value: "savadb_order"
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: mysqlorderdb
      volumes:
        - name: mysqlorderdb
          persistentVolumeClaim:
            claimName: mysql-order-claim
---
apiVersion: v1
kind: Service
metadata:
  name: ord-mysql-clusterip-srv
spec:
  type: ClusterIP
  selector:
    app: mysql-order
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
---
apiVersion: v1
kind: Service
metadata:
  name: ord-mysql-loadbalancer-srv
spec:
  type: LoadBalancer
  selector:
    app: mysql-order
  ports:
    - protocol: TCP
      port: 33063
      targetPort: 3306
