apiVersion: apps/v1
kind: Deployment
metadata:
  name: apigateway-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ocelotapigateway
  template:
    metadata:
      labels:
        app: ocelotapigateway
    spec:
      containers:
        - name: ocelotapigateway
          image: alexivanov01/ocelotapigateway:latest
---
apiVersion: v1
kind: Service
metadata:
  name: apigateway-clusterip-srv
spec:
  type: ClusterIP
  selector:
    app: ocelotapigateway
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
